# Generated by Django 5.2.6 on 2025-10-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_course_short_description_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='instructor_profiles/', verbose_name='Profile Picture'),
        ),
    ]
