# Generated by Django 5.2.6 on 2025-10-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_course_coursemodule_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.AddField(
            model_name='course',
            name='course_video',
            field=models.FileField(blank=True, null=True, upload_to='course_videos/'),
        ),
        migrations.AddField(
            model_name='course',
            name='notes_file',
            field=models.FileField(blank=True, null=True, upload_to='course_notes/'),
        ),
        migrations.AddField(
            model_name='course',
            name='outline',
            field=models.TextField(blank=True, verbose_name='Course Outline'),
        ),
    ]
