# Generated by Django 5.2.6 on 2025-10-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='instructor_id',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
    ]
